### ISSUE TITLE
Arena end/round revive not reviving

### ISSUE THREAD

**Issue by AimlessRex** [Anreol/VoidQoL#2]
At the end of round and end of arena players are not revived

**Comment by Anreol** [comment]
That feature in the config is disabled by default, sure it was enabled?

**Comment by AimlessRex** [comment]
I'm pretty sure it was enabled but i will double check and test it again

**Comment by Anreol** [comment]
Should be fixed in the latest update, feel free to reopen another issue if it breaks (somehow) again.
