### ISSUE TITLE
going to the void fields at stage 6+ won't spawn any enemies when activating the cells

### ISSUE THREAD

**Issue by Littleevo** [Anreol/VoidQoL#3]
![image](https://user-images.githubusercontent.com/79082772/157079729-98ed2ea8-baeb-4d8d-bbd0-ded6c3ad7e87.png)
here is the log. maybe it isn't related to your mod, but it's the closest thing i could find

**Comment by Anreol** [comment]
![imagen](https://user-images.githubusercontent.com/12176932/157110655-0c88dabc-ae14-4c65-8753-1c9335c9370d.png)
Been playing alone with just my mod and debug toolkit and it works just fine.
As I said, I experienced this error myself when playing with a big modpack, so there's either a bug with one mod you were playing with or with R2API that breaks directors in some kind of way
