### ISSUE TITLE
[Suggestion] Add configuration option for adjusting how much charge holdout zones get from killing monsters and for how long monsters should have a speedboost upon spawning.

### ISSUE THREAD

**Issue by PetMudstone** [Anreol/VoidQoL#6]
Title. The original VoidFieldsQoL mod had configuration options for how much charge killing an enemy gave to the holdout zones in the void fields and how long the speedboost on initial spawning lasts for. 
Making these variables adjustable would allow players to better get the kind of experience they want with the mod. Some people may want charge to increase on monster kill but think the default value is too high for example.

**Comment by Anreol** [comment]
Sure, package updated.
